const fs = require('fs');
const file = 'Avance2135.html';
let content = fs.readFileSync(file, 'utf8');

// The block to replace is everything between {/* MÓDULOS DE INGENIERÍA DE MENÚ Y FINANZAS */} and Importacion Masiva's old section
const regexCards = /\{\/\*\s*MÓDULOS DE INGENIERÍA DE MENÚ Y FINANZAS\s*\*\/\}[\s\S]*?(?=\{\/\* Importación Masiva — debajo del banner \*\/\}|$)/;

// The block of the Importacion Masiva to capture
const regexImport = /\{\/\*\s*Importación Masiva — debajo del banner\s*\*\/\}[\s\S]*?(?=\{\/\*\s*──\s*ACORDEÓN\s*1:\s*CATEGORÍAS\s*──\s*\*\/\}|$)/;

const matchImport = content.match(regexImport);
if (!matchImport) {
   console.log('Could not find Importacion Masiva block. It may have already been moved.');
}

const matchCards = content.match(regexCards);

// We replace these blocks if they exist:
let rawImport = matchImport ? matchImport[0].trim() : '';

const newTop = rawImport + `

           {/* CATEGORÍA BASE — Estructura del Menú */}
           <div className="mb-6 mt-4">
              <h3 className="text-xl font-bold border-b border-gray-200 pb-2 mb-2 text-slate-800">CATEGORÍA BASE — Estructura del Menú</h3>
              <p className="text-sm text-gray-500 mb-4">Se configura una vez. Es la base de todo lo demás.</p>
           </div>
`;

if (matchCards && matchImport) {
    content = content.replace(regexCards, '');
    content = content.replace(regexImport, newTop);
}


const appendABCRegex = /(\{\/\*\s*──\s*ACORDEÓN\s*4:\s*RECETAS\s*──\s*\*\/\}[\s\S]*?<MenuRecetasBlock[\s\S]*?\/>\s*<\/div>\s*\)\}\s*<\/div>)/;

const matchAppend = content.match(appendABCRegex);
if (!matchAppend) {
   console.log('Could not find Accordion 4 block properly.');
   process.exit(1);
}

const rentabilidad = `             <div className="bg-white border text-left border-gray-200 rounded-2xl p-5 hover:shadow-lg transition-all duration-300 group hover:border-purple-200">\n                <div className="flex items-center gap-3 mb-3">\n                   <div className="w-10 h-10 rounded-xl bg-purple-50 flex items-center justify-center text-purple-600 text-lg group-hover:bg-purple-600 group-hover:text-white transition-colors">✨</div>\n                   <h4 className="text-sm font-black text-slate-800">Simulador de Rentabilidad</h4>\n                </div>\n                <p className="text-xs text-gray-500 leading-relaxed mb-4">¿Qué pasa con tu margen si un insumo sube un 10%? ¿A qué precio debes vender para mantener el margen objetivo? Proyecta escenarios antes de que el problema llegue a la caja.</p>\n                <div className="flex flex-wrap gap-1.5">\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Finanzas</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Recetas e Inventario</span>\n                </div>\n             </div>`;

const costosProv = `             <div className="bg-white border text-left border-gray-200 rounded-2xl p-5 hover:shadow-lg transition-all duration-300 group hover:border-emerald-200">\n                <div className="flex items-center gap-3 mb-3">\n                   <div className="w-10 h-10 rounded-xl bg-emerald-50 flex items-center justify-center text-emerald-600 text-lg group-hover:bg-emerald-600 group-hover:text-white transition-colors">📈</div>\n                   <h4 className="text-sm font-black text-slate-800">Actualización Automática de Costos por Proveedor</h4>\n                </div>\n                <p className="text-xs text-gray-500 leading-relaxed mb-4">Cuando el precio de un insumo cambia, todos los platos que lo contienen se recalculan en tiempo real. Si el margen cae del objetivo, el sistema alerta de inmediato.</p>\n                <div className="flex flex-wrap gap-1.5">\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Proveedores</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Recetas e Inventario</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Finanzas</span>\n                </div>\n             </div>`;

const costoTeorico = `             <div className="bg-white border border-gray-200 text-left rounded-2xl p-5 hover:shadow-lg transition-all duration-300 group hover:border-blue-200">\n                <div className="flex items-center gap-3 mb-3">\n                   <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center text-blue-600 text-lg group-hover:bg-blue-600 group-hover:text-white transition-colors">⚖️</div>\n                   <h4 className="text-sm font-black text-slate-800">Costo Teórico vs. Costo Real</h4>\n                </div>\n                <p className="text-xs text-gray-500 leading-relaxed mb-4">Compara lo que debió gastarse según las recetas con lo que realmente se gastó según el inventario físico. La diferencia revela desperdicios, porciones mal servidas o fugas.</p>\n                <div className="flex flex-wrap gap-1.5">\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Inventario</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Finanzas</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🧠 Brain IA</span>\n                </div>\n             </div>`;

const bcg = `             <div className="bg-white border text-left border-gray-200 rounded-2xl p-5 hover:shadow-lg transition-all duration-300 group hover:border-orange-200">\n                <div className="flex items-center gap-3 mb-3">\n                   <div className="w-10 h-10 rounded-xl bg-orange-50 flex items-center justify-center text-orange-600 text-lg group-hover:bg-orange-600 group-hover:text-white transition-colors">⭐</div>\n                   <h4 className="text-sm font-black text-slate-800">Clasificación BCG del Plato</h4>\n                </div>\n                <p className="text-xs text-gray-500 leading-relaxed mb-4">Clasifica automáticamente cada plato como Estrella, Caballo de Batalla, Puzle o Perro según su rentabilidad y popularidad. Decide qué promover, reformular o retirar de la carta.</p>\n                <div className="flex flex-wrap gap-1.5">\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Ventas Hoy</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Finanzas</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🧠 Brain IA</span>\n                </div>\n             </div>`;

const fugas = `             <div className="bg-white border text-left border-gray-200 rounded-2xl p-5 hover:shadow-lg transition-all duration-300 group hover:border-red-200">\n                <div className="flex items-center gap-3 mb-3">\n                   <div className="w-10 h-10 rounded-xl bg-red-50 flex items-center justify-center text-red-600 text-lg group-hover:bg-red-600 group-hover:text-white transition-colors">🚨</div>\n                   <h4 className="text-sm font-black text-slate-800">Alerta de Detección de Fugas</h4>\n                </div>\n                <p className="text-xs text-gray-500 leading-relaxed mb-4">Detecta cuando el consumo real de un ingrediente no coincide con lo que debería haberse usado según las ventas. Señal automática de robo, desperdicio o error en porciones.</p>\n                <div className="flex flex-wrap gap-1.5">\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Inventario</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Ventas Hoy</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🧠 Brain IA</span>\n                </div>\n             </div>`;

const stockMinimo = `             <div className="bg-white border border-gray-200 text-left rounded-2xl p-5 hover:shadow-lg transition-all duration-300 group hover:border-teal-200">\n                <div className="flex items-center gap-3 mb-3">\n                   <div className="w-10 h-10 rounded-xl bg-teal-50 flex items-center justify-center text-teal-600 text-lg group-hover:bg-teal-600 group-hover:text-white transition-colors">📦</div>\n                   <h4 className="text-sm font-black text-slate-800">Stock Actual vs. Stock Mínimo por Insumo</h4>\n                </div>\n                <p className="text-xs text-gray-500 leading-relaxed mb-4">Monitorea en tiempo real cuánto hay de cada ingrediente y dispara una alerta de reorden antes de que se agote. Evita cortar platos en servicio y perder ventas.</p>\n                <div className="flex flex-wrap gap-1.5">\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Inventario</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Operaciones</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Proveedores</span>\n                </div>\n             </div>`;

const mermas = `             <div className="bg-white border border-gray-200 text-left rounded-2xl p-5 hover:shadow-lg transition-all duration-300 group hover:border-yellow-300">\n                <div className="flex items-center gap-3 mb-3">\n                   <div className="w-10 h-10 rounded-xl bg-yellow-50 flex items-center justify-center text-yellow-600 text-lg group-hover:bg-yellow-500 group-hover:text-white transition-colors">🔪</div>\n                   <h4 className="text-sm font-black text-slate-800">Factor de Rendimiento y Merma</h4>\n                </div>\n                <p className="text-xs text-gray-500 leading-relaxed mb-4">Registra cuánto del ingrediente que compras realmente terminas usando tras limpieza, cocción o corte. Sin este dato, el costo real de cada plato está subestimado.</p>\n                <div className="flex flex-wrap gap-1.5">\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Inventario</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Recetas e Inventario</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Finanzas</span>\n                </div>\n             </div>`;

const subRecetas = `             <div className="bg-white border text-left border-gray-200 rounded-2xl p-5 hover:shadow-lg transition-all duration-300 group hover:border-pink-200">\n                <div className="flex items-center gap-3 mb-3">\n                   <div className="w-10 h-10 rounded-xl bg-pink-50 flex items-center justify-center text-pink-600 text-lg group-hover:bg-pink-600 group-hover:text-white transition-colors">🥣</div>\n                   <h4 className="text-sm font-black text-slate-800">Recetas Intermedias o Sub-recetas</h4>\n                </div>\n                <p className="text-xs text-gray-500 leading-relaxed mb-4">Registra salsas, fondos o masas que se producen en lote y luego se usan como ingrediente en varios platos. Hace visible el costo de producción que ocurre antes del servicio.</p>\n                <div className="flex flex-wrap gap-1.5">\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Recetas e Inventario</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Inventario</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Operaciones</span>\n                </div>\n             </div>`;

const integracionPos = `             <div className="bg-white border text-left border-gray-200 rounded-2xl p-5 hover:shadow-lg transition-all duration-300 group hover:border-indigo-200">\n                <div className="flex items-center gap-3 mb-3">\n                   <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center text-indigo-600 text-lg group-hover:bg-indigo-600 group-hover:text-white transition-colors">💻</div>\n                   <h4 className="text-sm font-black text-slate-800">Integración con POS</h4>\n                </div>\n                <p className="text-xs text-gray-500 leading-relaxed mb-4">Cada venta descuenta automáticamente los ingredientes del inventario según la receta del plato vendido. Sin esta integración, el stock siempre estará desactualizado.</p>\n                <div className="flex flex-wrap gap-1.5">\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Ventas Hoy</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Inventario</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Operaciones</span>\n                </div>\n             </div>`;

const conversionUy = `             <div className="bg-white border text-left border-gray-200 rounded-2xl p-5 hover:shadow-lg transition-all duration-300 group hover:border-cyan-200">\n                <div className="flex items-center gap-3 mb-3">\n                   <div className="w-10 h-10 rounded-xl bg-cyan-50 flex items-center justify-center text-cyan-600 text-lg group-hover:bg-cyan-600 group-hover:text-white transition-colors">⚖️</div>\n                   <h4 className="text-sm font-black text-slate-800">Conversión de Unidades de Compra vs. Unidades de Receta</h4>\n                </div>\n                <p className="text-xs text-gray-500 leading-relaxed mb-4">El sistema traduce automáticamente entre la unidad en que compras (bulto, caja, litro) y la unidad en que cocinas (gramos, mililitros, unidades). El costo unitario siempre será exacto.</p>\n                <div className="flex flex-wrap gap-1.5">\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Proveedores</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Recetas e Inventario</span>\n                   <span className="text-[9px] font-bold px-2 py-0.5 rounded-md bg-gray-100 text-gray-600 border border-gray-200">🔄 Inventario</span>\n                </div>\n             </div>`;


const categoriesABC = "\n\n           {/* CATEGORÍA A — Inteligencia Financiera */}\n           <div className=\"mt-12 mb-6\">\n              <h3 className=\"text-xl font-bold border-b border-gray-200 pb-2 mb-2 text-indigo-900\">CATEGORÍA A — Inteligencia Financiera</h3>\n              <p className=\"text-sm text-gray-500 mb-4\">¿Estoy ganando o perdiendo dinero con cada plato?</p>\n              \n              <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-4\">\n" + rentabilidad + "\n" + costosProv + "\n" + costoTeorico + "\n" + bcg + "\n              </div>\n           </div>\n\n           {/* CATEGORÍA B — Control de Cocina y Producción */}\n           <div className=\"mt-12 mb-6\">\n              <h3 className=\"text-xl font-bold border-b border-gray-200 pb-2 mb-2 text-emerald-900\">CATEGORÍA B — Control de Cocina y Producción</h3>\n              <p className=\"text-sm text-gray-500 mb-4\">¿Estoy cocinando al costo correcto y sin pérdidas ocultas?</p>\n\n              <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4\">\n" + mermas + "\n" + subRecetas + "\n" + conversionUy + "\n              </div>\n           </div>\n\n           {/* CATEGORÍA C — Operaciones y Alertas en Tiempo Real */}\n           <div className=\"mt-12 mb-6\">\n              <h3 className=\"text-xl font-bold border-b border-gray-200 pb-2 mb-2 text-red-900\">CATEGORÍA C — Operaciones y Alertas en Tiempo Real</h3>\n              <p className=\"text-sm text-gray-500 mb-4\">¿Algo está fallando ahora mismo?</p>\n\n              <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4\">\n" + fugas + "\n" + stockMinimo + "\n" + integracionPos + "\n              </div>\n           </div>\n\n";

content = content.replace(appendABCRegex, matchAppend[0] + categoriesABC);

fs.writeFileSync(file, content, 'utf8');
console.log("Patch applied correctly!");
